name: Yarn Audit Fix Run

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: "Specify a base branch"
        required: false
        default: "main"
      package_manager:
        description: "Specify package manager (npm or yarn)"
        required: false
        default: "yarn"
      node_version:
        description: "Specify Node.js version"
        required: false
        type: string
        default: "24"
      script:
        description: "Specify the build script to run"
        required: false
        type: string
        default: "yarn build"
  
  schedule:
    - cron: "0 0 * * 1"

jobs:
  audit-fix:
    uses: step-security/reusable-workflows/.github/workflows/audit_fix.yml@fix_Verify_cherry_pick-Logic
    with:
      base_branch: ${{ inputs.base_branch || 'main' }}
      package_manager: "yarn"
      node_version: ${{ inputs.node_version || '24' }}
      script: ${{ inputs.script || 'yarn build' }}

permissions:
  contents: write
  pull-requests: write
  packages: read
  issues: write
